---
controller_hosts:
  - '['
  - '['
  - '{'
  - ''''
  - n
  - a
  - m
  - e
  - ''''
  - ':'
  - ' '
  - ''''
  - h
  - o
  - s
  - t
  - '2'
  - ''''
  - ','
  - ' '
  - ''''
  - d
  - e
  - s
  - c
  - r
  - i
  - p
  - t
  - i
  - o
  - n
  - ''''
  - ':'
  - ' '
  - ''''
  - ''''
  - ','
  - ' '
  - ''''
  - i
  - n
  - v
  - e
  - n
  - t
  - o
  - r
  - y
  - ''''
  - ':'
  - ' '
  - ''''
  - D
  - e
  - m
  - o
  - ' '
  - I
  - n
  - v
  - e
  - n
  - t
  - o
  - r
  - y
  - ''''
  - '}'
  - ','
  - ' '
  - '{'
  - ''''
  - n
  - a
  - m
  - e
  - ''''
  - ':'
  - ' '
  - ''''
  - l
  - o
  - c
  - a
  - l
  - h
  - o
  - s
  - t
  - ''''
  - ','
  - ' '
  - ''''
  - d
  - e
  - s
  - c
  - r
  - i
  - p
  - t
  - i
  - o
  - n
  - ''''
  - ':'
  - ' '
  - ''''
  - ''''
  - ','
  - ' '
  - ''''
  - i
  - n
  - v
  - e
  - n
  - t
  - o
  - r
  - y
  - ''''
  - ':'
  - ' '
  - ''''
  - D
  - e
  - m
  - o
  - ' '
  - I
  - n
  - v
  - e
  - n
  - t
  - o
  - r
  - y
  - ''''
  - ','
  - ' '
  - ''''
  - v
  - a
  - r
  - i
  - a
  - b
  - l
  - e
  - s
  - ''''
  - ':'
  - ' '
  - '{'
  - ''''
  - a
  - n
  - s
  - i
  - b
  - l
  - e
  - _
  - c
  - o
  - n
  - n
  - e
  - c
  - t
  - i
  - o
  - n
  - ''''
  - ':'
  - ' '
  - ''''
  - l
  - o
  - c
  - a
  - l
  - ''''
  - '}'
  - '}'
  - ']'
  - ','
  - ' '
  - '['
  - '{'
  - ''''
  - n
  - a
  - m
  - e
  - ''''
  - ':'
  - ' '
  - ''''
  - '1'
  - '0'
  - .
  - '1'
  - '0'
  - .
  - '1'
  - '0'
  - .
  - '1'
  - ''''
  - ','
  - ' '
  - ''''
  - d
  - e
  - s
  - c
  - r
  - i
  - p
  - t
  - i
  - o
  - n
  - ''''
  - ':'
  - ' '
  - ''''
  - i
  - p
  - ' '
  - h
  - o
  - s
  - t
  - ''''
  - ','
  - ' '
  - ''''
  - i
  - n
  - v
  - e
  - n
  - t
  - o
  - r
  - y
  - ''''
  - ':'
  - ' '
  - ''''
  - u
  - p
  - g
  - r
  - a
  - d
  - e
  - ''''
  - '}'
  - ','
  - ' '
  - '{'
  - ''''
  - n
  - a
  - m
  - e
  - ''''
  - ':'
  - ' '
  - ''''
  - h
  - o
  - s
  - t
  - '3'
  - ''''
  - ','
  - ' '
  - ''''
  - d
  - e
  - s
  - c
  - r
  - i
  - p
  - t
  - i
  - o
  - n
  - ''''
  - ':'
  - ' '
  - ''''
  - m
  - y
  - ' '
  - t
  - h
  - i
  - r
  - d
  - ' '
  - h
  - o
  - s
  - t
  - ''''
  - ','
  - ' '
  - ''''
  - i
  - n
  - v
  - e
  - n
  - t
  - o
  - r
  - y
  - ''''
  - ':'
  - ' '
  - ''''
  - u
  - p
  - g
  - r
  - a
  - d
  - e
  - ''''
  - ','
  - ' '
  - ''''
  - v
  - a
  - r
  - i
  - a
  - b
  - l
  - e
  - s
  - ''''
  - ':'
  - ' '
  - '{'
  - ''''
  - v
  - a
  - r
  - '1'
  - ''''
  - ':'
  - ' '
  - ''''
  - t
  - e
  - s
  - t
  - ''''
  - '}'
  - '}'
  - ']'
  - ']'
