---
- name: "Playbook to upgrade CaC from AAP <= 2.4 to AAP >= 2.5 format"
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    software_repository: https://{{ personal_access_token }}@github.com/ericcames/aap24_conversion_factory.git
    personal_access_token: git_hub_token
    local_repo: /var/tmp/github/aap24_conversion_factory
    git_name: ericcames
    git_email: ericcames@msn.com

  tasks:

    - name: Clone the software repository
      register: clone_result
      run_once: true
      when: software_repository is defined
      ansible.builtin.git:
        repo: "{{ software_repository }}"
        dest: "{{ local_repo }}"
        accept_hostkey: true
        force: true
        version: main

    - name: Call upgrade_config role
      vars:
        # input_authenticator_name: "IDM LDAP"
        aap24_configs_dir: "{{ local_repo }}/aap24_configs_copy"
        aap25_configs_dir: "{{ local_repo }}/aap25_configs"
      ansible.builtin.include_role:
        name: infra.aap_configuration_extended.upgrade_config

    - name: Add any new playbooks to the software_repository
      changed_when: false
      run_once: true
      args:
        chdir: "{{ local_repo }}"
      ansible.builtin.shell: git add *

    - name: Get the status of the repository
      register: status_results
      changed_when: false
      ignore_errors: true
      run_once: true
      args:
        chdir: "{{ local_repo }}"
      ansible.builtin.shell: git status

    - name: Commit the changes
      when: status_results.stdout is search('Changes')
      run_once: true
      environment:
        GIT_COMMITTER_NAME: "{{ git_name | default(omit) }}"
        GIT_COMMITTER_EMAIL: "{{ git_email | default(omit) }}"
        GIT_AUTHOR_NAME: "{{ git_name | default(omit) }}"
        GIT_AUTHOR_EMAIL: "{{ git_email | default(omit) }}"
      args:
        chdir: "{{ local_repo }}"
      ansible.builtin.shell: git commit -am 'New AAP 2.5 code'

    - name: Push the changes
      run_once: true
      when: software_repository is defined
      args:
        chdir: "{{ local_repo }}"
      ansible.builtin.shell: git push
